### ISSUE TITLE
[enchancement]compacting draw option?

### ISSUE THREAD

**Issue by Layarion** [Funwayguy/BarrelsDrumsStorageAndMore#1]
haven't looked at this mod enough yet to know, but if this can also fulfill the role of compacting drawers, that would be great.

what would be better, is if it could do more than 3 items if an item happens to have more than 3 things it can go into and reverse into.

**Comment by Funwayguy** [comment]
I'm not going to be copying Storage Drawers. I have other plans for this mod and its job is neither to replace drawers nor is it meant to provide end game level of storage options.
