### ISSUE TITLE
Withdraw Fluid?

### ISSUE THREAD

**Issue by geong1** [Funwayguy/BarrelsDrumsStorageAndMore#10]
Cannot withdraw fluid (lava) with a bucket from a drum.
Tried left and right clicking. Sneak and not sneaking.

Most up to date version (Sky Factory 4.0.2)

**Comment by Durandle** [comment]
i have had this issue also i initially assumed it was just intended when i was using wooden barrels but i was able to withdraw buckets of lava from an iron drum perfectly fine


that was until it filled up and it stopped letting me withdraw lava from it

**Comment by geong1** [comment]
Can confirm:
1: You CAN withdraw from a iron drum filled with lava (the only fluid I've tested) IF it is not all the way full.

2: You CANNOT withdraw from an iron drum (full or not) if you have multiple buckets in your hand (a stack of 4 buckets)

3: You CAN withdraw from an iron drum (not full) if you have an item like a diamond bucket and you left/right click the drum.

**Comment by Funwayguy** [comment]
Confirmed this happens in dev. I accidentally copied the insertion math as the withdraw cap. Should have a fix out later today.
