### ISSUE TITLE
If player's inventory is full, retrieving items from wooden crate will just void the item.

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [Funwayguy/BarrelsDrumsStorageAndMore#11]
I have a 64x64 wooden crate with all logs in it, I was trying to clear it out when I take all the logs. Initially I thought when my inventory was full, the crate will simply spill out stacks of woods. But when I continuously left click it, the logs inside the crate is deleted, but it wasn't added in my inventory. I suggest a check to see if inventory is full, and simply spill it.

**Comment by Funwayguy** [comment]
Were you in creative mode by chance?

**Comment by Pythonic-Rainbow** [comment]
No

**Comment by SereneRebel** [comment]
Also confirm this behaviour with the skyfactory 4 modpack, all stock, default settings

**Comment by Funwayguy** [comment]
I still can't recreate this in builds 0.0.22 of the mod (at least by itself). Crates automatically dump withdrawn items onto the ground if they can't fit.

**Comment by SereneRebel** [comment]
Re-checked and the SF4 pack is still using 0.0.21 this could be why 
Thankyou

**Comment by Pythonic-Rainbow** [comment]
@Funwayguy yeah , I am playing SF4 too. v4.0.2 is using v0.0.21 whereas v4.0.3 will be using v0.0.22. Hopefully we can test if the bug still exists in 4.0.3, thus confirming if 0.0.22 still suffers from it.

Tho if u can't recreate, I am pretty sure the bug is fixed in 0.0.22

**Comment by Funwayguy** [comment]
Going to close this seeing as I still carn't recreate this and SF4 has been updated since
