### ISSUE TITLE
Double clicking to retrieve a stack is terrrible imo

### ISSUE THREAD

**Issue by Coirt** [Funwayguy/BarrelsDrumsStorageAndMore#13]
Not sure if this intended behaviour or a bug but with the latest update the user now has to double click to retrieve a stack of items this makes retrieval for automation slow: for example it interferes with how Thermal Dynamics interacts with stacks, because the barrel can't output a stack it outputs 1 item rendering itemducts useless.

An option in the config would be a nice addition, shift clicking for a stack or shift clicking for 1 item would be most desirable.

**Comment by Funwayguy** [comment]
First, how the heck does a player's interaction affect an Item Duct? Those two functions should have nothing to do with eachother. Any pipe should be able to request whatever stack size it wants. Heck dump the whole barrel contents in one go and blow the stack limit, crates doesn't care.

Second, this is the 8th time someone has complained about the controls and requested a change. Nobody can agree on anything and this is the closest middle ground I've found without conflicting with block breaking and shift clicking block placements. I can spam click to fill my inventory in a few seconds too so I'm not sure what your idea of slow is.

Finally, the interaction is currently controlled serverside and cannot be personalized client side without having to rewrite a portion of the mod. Doing so would not be in the interest of SF4's stability updates either, especially if it'll break something.

**Comment by Coirt** [comment]
I never said player interaction effects it, I said because you have to double click to extract a stack TD ducts are effected by the change, they will no longer extract a stack or whatever the installed servo asks for. The most a reinforced servo for example can extract is 3 items at a time (should be 32). Iv'e no idea why that would happen but the item ducts worked fine before the update.

Perhaps multiple people are complaining because the mod tries to replace other mods that have those features and they can be configured to suit taste.

I'm on client it broke something! Item ducts. It's pretty simple having to shift click to grab a stack or configured to shift click to grab 1 item would please everyone. I only report it because it was fine before the update though not having the config option would be fine also, the previous versions interaction was okay imo. (shift click to grab a stack, either way I couldn't care less)
