### ISSUE TITLE
[Suggestion] Apply a stack of upgrades

### ISSUE THREAD

**Issue by Mac15001900** [Funwayguy/BarrelsDrumsStorageAndMore#14]
It currently takes 512 right-click actions, or about 100 seconds, to fully upgrade a metal crate with x64 upgrades. It'd be very helpful if you could apply an entire stack of upgrades at once, perhaps by shift-right-clicking.

**Comment by Funwayguy** [comment]
You know you could have saved yourself the effort and combine them into a bigger upgrade.

Unless you're playing with SF4 in which case they have custom recipes and possibly disabled upgrade combining.

**Comment by Mac15001900** [comment]
Yes, this is in SF4, I didn't know that you can normally combine them. I guess it's not really an issue then - normally you can combine them, and SF4 has auto-clickers.
