### ISSUE TITLE
OBJLoaderColored and OBJModelColored missing

### ISSUE THREAD

**Issue by MrHDR** [Funwayguy/BarrelsDrumsStorageAndMore#18]
Hey, just wondering if the obj package with OBJLoaderColored and OBJModelColored are missing on purpose? as it stands i'm not able to compile the mod.

**Comment by Funwayguy** [comment]
It isn't missing on purpose, likely an oversight with the git ignore file. You can swap it to the uncolored kind if you're just testing something.

Can I ask what you intend to do with this mod?

**Comment by MrHDR** [comment]
The plan was to compile a custom version with the fixes you've added and run it on our server.

**Comment by Funwayguy** [comment]
You do know you're not really supposed to build and share your own custom version of the mod as per its default license right? Not really sure why you'd need to in the first place. If it's a bug fix or general improvement then a PR is how you'd go about that.

**Comment by MrHDR** [comment]
Wasn't intending on sharing it, as it stands with Minecraft you can compile a mod version as another version (like compiling 0.23 as 0.22), and it will work fine on servers in most caes, while fixing bugs, and letting people join.

**Comment by Funwayguy** [comment]
Mod has been updated to 0.0.24 and the git ignore file has been fixed. I'm still not changing the license though so the only way you're properly allowed to provide bug fixes is through a pull request.

Just so you know, you're not going to be able to run 0.0.24 with an older client just by changing the version number. Even if it doesn't crash, the containers will likely not respond properly or at all.
