### ISSUE TITLE
[newcomers issue]documentation is a bit lacking

### ISSUE THREAD

**Issue by Layarion** [Funwayguy/BarrelsDrumsStorageAndMore#2]
there needs to be more in-game tooltips and stuff to explain what each feature and block does. as well as out of game. i don't know how to use the large crate.

**Comment by Funwayguy** [comment]
A short tooltip was added to the shipping container item however its actual use cases are too wide to summarise accurately. The rest of the crates, barrels and upgrades are pretty self explanatory.

**Comment by LlubNek** [comment]
You should add a wiki (here in GitHub, or in Curseforge).
