### ISSUE TITLE
Recipes Missing and Odd Behavior with CarryOn

### ISSUE THREAD

**Issue by Sixdd6** [Funwayguy/BarrelsDrumsStorageAndMore#5]
Recipes are missing for the Wooden Barrel and Metal Crate.

When crates are picked up and placed back down with CarryOn the side with the item display only faces a certain direction rather than facing toward the player which makes it somewhat annoying to move crates and maintain some sort of order. I also noticed that after the crates have been picked up and placed back down the side that the item display is on can change after removing and replacing the items inside the crate. So basically, place crate, put item in crate, pick up crate, place crate, note side of crate that item display is on, remove item from crate, deposit item back into crate, the item display is now on a different side.

instance details:
forge-1.12.2-14.23.5.2836
BDSM 0.0.19
CarryOn 1.12.1

[latest.log](https://gist.github.com/Sixdd6/ffcf1815bae0a0f75f8604e69765e2ed)

**Comment by Sixdd6** [comment]
After a bit of further testing I think what's happening is when the crate is placed back down the facing does not update on the item display but the crate itself does update. After several tests, each time I deposit the item back into the crate after picking it up the face the display shows on is relative to the direction I was facing when placing the barrel down. It's too late, need sleep..

**Comment by Funwayguy** [comment]
Fixed this one in dev but for build 23 not 22. Although the crates and barrels work fine with CarryOn now, the shipping containers still break pretty badly. May just have to blacklist them.
