### ISSUE TITLE
Once Placed, Empty Crates cannot be used to craft

### ISSUE THREAD

**Issue by LezChap** [Funwayguy/BarrelsDrumsStorageAndMore#6]
I made some wooden crates, then upgraded to metal ones, which involved emptying the wooden crates.  The wooden crates, which now show Empty, cannot be used to craft metal crates.

**Comment by Funwayguy** [comment]
Is this specific to Sky Factory 4's custom recipes or the built in defaults? If you're using the built in ones, try using build 0.0.22

**Comment by LezChap** [comment]
I didn't realize SF customized the recipes for the Crates, I'll refer it to them, thanks.

**Comment by ttv-trie** [comment]
@LezChap Were you able to get some information from SF?

**Comment by ttv-trie** [comment]
@Funwayguy I'm curious as to why when a crate is first crafted it has NBT data:
`<bdsandm:wood_crate>.withTag({crateCap: {maxCap: 1024, objColors: [-1, -1] as int[], oreDict: 0 as byte, overflow: 0 as byte, refStack: {id: "minecraft:air", Count: 1 as byte, Damage: 0 as short}, count: 0, locked: 0 as byte, stackCap: 64}})`

If you place it and pick it back up the NBT stays the same, but if you insert and item and remove it then pick it up it has a different count:
`<bdsandm:wood_crate>.withTag({crateCap: {maxCap: 1024, objColors: [-1, -1] as int[], oreDict: 0 as byte, overflow: 0 as byte, refStack: {id: "minecraft:air", Count: 0 as byte, tag: {}, Damage: 0 as short}, count: 0, locked: 0 as byte, stackCap: 64`

**Comment by mbrucher** [comment]
The problem still exists (SF4). Not sure why it would be SF4 problem to reset the tags when the crate is emptied?

**Comment by Xiang990293** [comment]
This issue still exist but in different ways on 0.0.24 1.12.2.

Here is an explanation. If I had put a stack of item in an wooden crate and empty it then, the NBT of it will transform from `...refStack:{item:"minecraft:air", Count:1b, Damage:0s}...` to `...refStack:{item:"minecraft:air", Count:0b, Damage:0s}...` .

The one that is craftable is the one that have one air in it.
