### ISSUE TITLE
Can't empty liquids from barrel/drum

### ISSUE THREAD

**Issue by VallenFrostweaver** [Funwayguy/BarrelsDrumsStorageAndMore#7]
Upon using a bucket to put liquids in a drum or barrel I can't bucket the liquid back out.

Forge 14.23.5.2836
BDS&M: 0.0.19

**Comment by Funwayguy** [comment]
In that version it's left click similar to how you'd withdraw items. I'm changing it next build to allow for right click if the container is already empty.

**Comment by Funwayguy** [comment]
build 21 is live with the change
