### ISSUE TITLE
Uninstall Upgrades

### ISSUE THREAD

**Issue by joshrpg** [Funwayguy/BarrelsDrumsStorageAndMore#8]
Does the crate need to be empty before an upgrade needs to be removed? 

Edit: I figured out it does. Suggestion, adding a tooltip would be helpful.

**Comment by scotty9090** [comment]
So how do you remove them?

**Comment by md5i** [comment]
Thanks.  I thought I was experiencing a bug.  It would be nice if it would remove modules until/unless the remaining state would be illegal otherwise.

**Comment by Kuperus** [comment]
i haven`t yet… how can you remove upgrades?

**Comment by md5i** [comment]
Empty the container and then use the remove upgrade item on it.

**Comment by Kuperus** [comment]
LOL... as i got the msg you wrote i just found the item in SF4 :) tnx anyway!
